In [16]:
import numpy as np
array_1d = np.arange(10, 51)
print(array_1d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [17]:
random_array = np.random.rand(3, 3)
print(random_array)

[[0.72820577 0.61385899 0.34742516]
 [0.83967002 0.79963823 0.05626278]
 [0.79095839 0.2126127  0.23205557]]


In [18]:
shape = random_array.shape
size = random_array.size
dtype = random_array.dtype
print(shape)
print(size)
print(dtype)

(3, 3)
9
float64


In [19]:
modified_array = array_1d + 5
print(modified_array)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [20]:
array_2d_1 = np.array([[1, 2], [3, 4]])
array_2d_2 = np.array([[5, 6], [7, 8]])
elementwise_multiplication = array_2d_1 * array_2d_2
print(elementwise_multiplication)

[[ 5 12]
 [21 32]]


In [21]:
array_5x5 = np.arange(1, 26).reshape(5, 5)
print(array_5x5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [22]:
first_row = array_5x5[0, :]
print(first_row)

[1 2 3 4 5]


In [23]:
last_column = array_5x5[:, -1]
print(last_column)

[ 5 10 15 20 25]


In [24]:
random_integers = np.random.randint(1, 101, size=10)
print(random_integers)

[80 23 95  6 65 14 19 13 68 62]


In [25]:
max_value = random_integers.max()
min_value = random_integers.min()
mean_value = random_integers.mean()
std_deviation = random_integers.std()
print(max_value)
print(min_value)
print(mean_value)
print(std_deviation)

95
6
44.5
30.99435432461854


In [26]:
array_1d_reshaped = np.arange(1, 13).reshape(3, 4)
print(array_1d_reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
matrix_of_ones = np.ones((3, 3))
array_to_add = np.array([1, 2, 3])
broadcasted_matrix = matrix_of_ones + array_to_add
print(broadcasted_matrix)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [28]:
random_array_1d = np.random.randint(1, 51, size=10)
divisible_by_5 = random_array_1d[random_array_1d % 5 == 0]
print(divisible_by_5)

[20  5]


In [29]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix_a, matrix_b)
print(matrix_product)

[[19 22]
 [43 50]]


In [32]:
array_4x4 = np.arange(1, 17).reshape(4, 4)
diagonal_elements = array_4x4[np.arange(4), np.arange(4)]
print(diagonal_elements)

[ 1  6 11 16]
